# Generated by Django 3.0.8 on 2020-09-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200903_0042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_followers',
            unique_together={('user', 'follower')},
        ),
    ]
