# Generated by Django 3.0.8 on 2020-09-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20200903_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Followers',
            new_name='Friendship',
        ),
    ]
